name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apksigner

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'gradle'

    - name: Write key
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
        echo ${{ secrets.KEY_STORE }} | base64 --decode > keystore.jks
        fi

    - name: Build with Gradle
      run: |
        if [ -f 'keystore.jks' ]; then
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file="$(pwd)/keystore.jks" \
            -Pandroid.injected.signing.store.password="${{ secrets.KEY_STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
        else
          ./gradlew assembleDebug
        fi
        

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: app/build/outputs/apk